import type { Metadata } from "next";
import { Space_Grotesk, Open_Sans, DM_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/themes/theme-provider";
import "./globals.css";

// Header font
const spaceGrotest = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

// Body font
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

// CTA font
const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${spaceGrotest.variable} ${dmSans.variable} ${openSans.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
